### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by SamDecrock** [MichaelQQ/dbfstream#2]
Hi,

How can I make the dbfstream wait for a callback?

Sam

**Comment by MichaelQQ** [comment]
Hi @SamDecrock,

Could you give me a code example?
Thank you.

**Comment by SamDecrock** [comment]
Could I do something like:

```js
dbf.on('data', (record, callback) => {
	saveToOtherDatabase(record, (err) => {
		callback();
	});
});
```

**Comment by MichaelQQ** [comment]
As your code snippet, the callback function would be called many times.

If I want to execute callback function after all data save to otherDatabase, I would get the number of record from header then tracking the latest record saving state.

```javascript
function transferRecords (dbfFilePath, callback) {
  // get the number of records
  dbf.on('header', header => {
    var numberOfRecord = header.numberOfRecord
  }

  // save dbf records to other database
  dbf.on('data', data => {
     saveToOtherDatabase(data, err => {
        if (data['@numOfRecord'] === numberOfRecord) {
          callback()
        }
     })
  }
}
```

**Comment by SamDecrock** [comment]
Actually, I want the dbf streamer to give me the first record, then I do an operation, and tell dbf streamer to give me the second record and so on... Is that possible?

**Comment by SamDecrock** [comment]
Actually, I want the dbf streamer to give me the first record, then I do an
operation, and tell dbf streamer to give me the second record and so on...
Is that possible?

2017-08-25 16:06 GMT+02:00 MichaelQQ <notifications@github.com>:

**Comment by MichaelQQ** [comment]
If so, I think you could do as follow.

```javascript
  dbf.on('data', (record) => {
    dbf.pause();
    saveToOtherDatabase(record, (err) => {
      dbf.resume();
     });
  });
```

**Comment by mickeyjohn** [comment]
Do .pause() and .resume() methods exist? 

Thanks for sharing the efficient dbf parser.
